name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Project-Env/project-env-github-action@v1.3.0
    - run: |
        npm ci
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}