name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The name of the version which should be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: Project-Env/project-env-github-action@v1.2.0
      with:
        cli-version: '3.7.1'
    - run: |
        npm ci
        npx expo-cli publish --non-interactive --release-channel production
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        GROW_BUDDY_VERSION: ${{ github.event.inputs.version }}
    - uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: v${{ github.event.inputs.version }}